############################################################################
# Custom configuration for finding files in WLTM Radio

default: &default
  # All paths used will be append to this path
  base_path: /mnt/space/

  # Files in these folders will be used for shuffling
  # Paths that include * will be passed through Dir.glob
  included_folders:
    - '**/wltmradio/'
    - 'another/path/here'

  # Only files with these extensions will be available to be queued
  allowed_extensions:
    - flac
    - wav
    - mp3
    - ogg
    - aac
    - aiff
    - mpa
    - m4a
    - wma
    - ape

  # Only allowed image extensions are used for images
  allowed_image_extensions:
    - jpg
    - jpeg
    - bmp
    - png
    - gif

  # Optional, if you want to enable downloading files via WebDAV, base path to WebDAV download service
  download_base_path: http://path/to/download/base

  # Optional, if you want to enable downloading entire folders, base path to
  download_folder_base_path: http://path/to/download/folder

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

