############################################################################
# Custom configuration for icecast configuration for monitoring

default: &default
  # Hostname for the icecast instance, usually localhost
  hostname: localhost

  # Port for the icecast instance, usually 8000
  port: 8000

  # Admin account password
  admin_password:

  # Base address for all icecast paths
  icecast_base: http://localhost:8000/

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default