############################################################################
# Custom configuration for interacting with MPD

default: &default
  # Local socket file for accessing MPD
  # NOTE: MPD via UNIX socket is the only supported method of connecting to MPD at this time
  socket: /run/mpd/socket

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default